// Auto-generated list of markdown files
// Generated: 2025-10-05T03:51:23.154Z
// 
// DO NOT EDIT THIS FILE MANUALLY!
// Run 'node generate-posts-index.js' to regenerate
//
// To add a new post:
// 1. Create your .md file in posts/exp/, posts/study/, or posts/dailynote/
// 2. Run: node generate-posts-index.js
// 3. Commit both the .md file and this file

const POST_FILES = [
    'posts/exp/sample-post copy.md',
    'posts/exp/sample-post.md',
    'posts/exp/Untitled.md'
];
