// Auto-generated list of markdown files
// Generated: 2025-10-05T05:26:23.786Z
// 
// DO NOT EDIT THIS FILE MANUALLY!
// Run 'node generate-posts-index.js' to regenerate
//
// To add a new post:
// 1. Create your .md file in posts/exp/, posts/study/, or posts/dailynote/
// 2. Run: node generate-posts-index.js
// 3. Commit both the .md file and this file

const POST_FILES = [
    'posts/exp/2025-10-05-oai-hcmc-2025-newbie.md'
];
